### ISSUE TITLE
compilation failure of android-simg2im (generate_verity_key) against openssl 1.1

### ISSUE THREAD

**Issue by maertsen** [mikeperry-tor/mission-improbable#27]
Compiling android-simg2im against openssl 1.1 fails, which results in a missing verity key; this does not currently stop the script. I have [reported upstream](https://github.com/anestisb/android-simg2img/issues/8), yet it seemed wise to make the issue visible here too.

**Comment by maertsen** [comment]
This was previously reported as https://github.com/mikeperry-tor/mission-improbable/issues/26, but closed without fix; apologies for the duplication.

**Comment by Girtab1352** [comment]
from what I can find here, this is where my current issue lives.  if not, please kindly redirect me.
short and sweet, running ./run_all.sh successfully installs only copperhead, no other apps, no root, and no gapps. At the end of the install, I get 
`Copperhead successfully installed!
~/Pets/mip/mission-improbable/angler-nmf26q ~/Pets/mip/mission-improbable
~/Pets/mip/mission-improbable
cp: cannot stat 'keys/verity_key.pub': No such file or directory`

I have painstakingly attempted this a few times, first from stock Android 7.1.1 on Nexus 6P, and every time since starting with an already unlocked bootloader and CopperheadOS installed (and working, minus every other feature from this project.)  Each time the result has been the same.

Here is the long log of all steps followed to this point.  I am using 
`Linux 3p1cpwn4g3 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
`
Log:
`[realname@3p1cpwn4g3 CopperWorkingDir]$ cd ~/Pets/mip/mission-improbable/
[realname@3p1cpwn4g3 mission-improbable]$ ls
angler-factory-2016.12.25.22.27.39.tar.xz      apply-gapps-delta.sh   fetch-apks.sh           gapps_filelist-7.0.txt  install-gapps.sh     keys                README.md   update.sh
angler-factory-2016.12.25.22.27.39.tar.xz.sig  clone-helper-repos.sh  flash-signed.sh         helper-repos            install-packages.sh  orwall-userinit.sh  re-sign.sh
apk_url_list.txt                               extras                 gapps_filelist-6.0.txt  install-copperhead.sh   install-su.sh        packages            run_all.sh
[realname@3p1cpwn4g3 mission-improbable]$ gpg --recv-keys 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
gpg: key F9E712E59AF5F22A: "Daniel Micay <danielmicay@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
[realname@3p1cpwn4g3 mission-improbable]$ gpg angler-factory-2016.12.25.22.27.39.tar.xz
angler-factory-2016.12.25.22.27.39.tar.xz      angler-factory-2016.12.25.22.27.39.tar.xz.sig  
[realname@3p1cpwn4g3 mission-improbable]$ gpg angler-factory-2016.12.25.22.27.39.tar.xz.sig 
gpg: assuming signed data in 'angler-factory-2016.12.25.22.27.39.tar.xz'
gpg: Signature made Sun 25 Dec 2016 06:50:20 PM CST
gpg:                using RSA key 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
gpg: Good signature from "Daniel Micay <danielmicay@gmail.com>" [unknown]
gpg:                 aka "Daniel Micay <daniel.micay@copperhead.co>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 65EE FE02 2108 E2B7 08CB  FCF7 F9E7 12E5 9AF5 F22A
[realname@3p1cpwn4g3 mission-improbable]$ tar -Jxvf angler-factory-2016.12.25.22.27.39.tar.xz
angler-nmf26q/
angler-nmf26q/image-angler-nmf26q.zip
angler-nmf26q/bootloader-angler-angler-03.62.img
angler-nmf26q/radio-angler-angler-03.78.img
angler-nmf26q/flash-all.sh
angler-nmf26q/flash-all.bat
angler-nmf26q/flash-base.sh
[realname@3p1cpwn4g3 mission-improbable]$ ./run_all.sh angler-nmf26q
Cloning android-simg2img and super-bootimg forks...
Cloning into '/home/realname/Pets/mip/mission-improbable/helper-repos/android-simg2img'...
remote: Counting objects: 112, done.
remote: Total 112 (delta 0), reused 0 (delta 0), pack-reused 112
Receiving objects: 100% (112/112), 79.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (44/44), done.
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude backed_block.c -o backed_block.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude output_file.c -o output_file.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude sparse.c -o sparse.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude sparse_crc32.c -o sparse_crc32.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude sparse_err.c -o sparse_err.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude sparse_read.c -o sparse_read.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude ext4_utils.c -o ext4_utils.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude ext4_sb.c -o ext4_sb.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude allocate.c -o allocate.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude indirect.c -o indirect.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude extent.c -o extent.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude crc16.c -o crc16.o
cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude sha1.c -o sha1.o
ar rc libsparse.a backed_block.o output_file.o sparse.o sparse_crc32.o sparse_err.o sparse_read.o ext4_utils.o ext4_sb.o allocate.o indirect.o extent.o crc16.o sha1.o
ranlib libsparse.a
cc -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude -o simg2img simg2img.c -L. -lsparse -lm -lz
cc -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude -o simg2simg simg2simg.c -L. -lsparse -lm -lz
make: *** No rule to make target 'img2simg.c$', needed by 'img2simg'.  Stop.
/home/realname/Pets/mip/mission-improbable
Cloning into '/home/realname/Pets/mip/mission-improbable/helper-repos/super-bootimg'...
remote: Counting objects: 1809, done.
remote: Total 1809 (delta 0), reused 0 (delta 0), pack-reused 1809
Receiving objects: 100% (1809/1809), 6.73 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (769/769), done.
--2016-12-29 19:35:57--  https://f-droid.org/repo/org.ethack.orwall_38.apk
Resolving f-droid.org (f-droid.org)... 107.150.51.2, 5.196.66.24
Connecting to f-droid.org (f-droid.org)|107.150.51.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3355954 (3.2M) [application/vnd.android.package-archive]
Saving to: â€˜org.ethack.orwall_38.apkâ€™

org.ethack.orwall_38.apk                             100%[=====================================================================================================================>]   3.20M  1.95MB/s    in 1.6s    

2016-12-29 19:35:59 (1.95 MB/s) - â€˜org.ethack.orwall_38.apkâ€™ saved [3355954/3355954]

--2016-12-29 19:35:59--  https://f-droid.org/repo/org.ethack.orwall_38.apk.asc
Resolving f-droid.org (f-droid.org)... 5.196.66.24, 107.150.51.2
Connecting to f-droid.org (f-droid.org)|5.196.66.24|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 648 [text/plain]
Saving to: â€˜org.ethack.orwall_38.apk.ascâ€™

org.ethack.orwall_38.apk.asc                         100%[=====================================================================================================================>]     648  --.-KB/s    in 0s      

2016-12-29 19:36:00 (111 MB/s) - â€˜org.ethack.orwall_38.apk.ascâ€™ saved [648/648]

--2016-12-29 19:36:00--  https://f-droid.org/repo/com.projectsexception.myapplist.open_16.apk
Resolving f-droid.org (f-droid.org)... 107.150.51.2, 5.196.66.24
Connecting to f-droid.org (f-droid.org)|107.150.51.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1718886 (1.6M) [application/vnd.android.package-archive]
Saving to: â€˜com.projectsexception.myapplist.open_16.apkâ€™

com.projectsexception.myapplist.open_16.apk          100%[=====================================================================================================================>]   1.64M  2.74MB/s    in 0.6s    

2016-12-29 19:36:01 (2.74 MB/s) - â€˜com.projectsexception.myapplist.open_16.apkâ€™ saved [1718886/1718886]

--2016-12-29 19:36:01--  https://f-droid.org/repo/com.projectsexception.myapplist.open_16.apk.asc
Resolving f-droid.org (f-droid.org)... 5.196.66.24, 107.150.51.2
Connecting to f-droid.org (f-droid.org)|5.196.66.24|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 665 [text/plain]
Saving to: â€˜com.projectsexception.myapplist.open_16.apk.ascâ€™

com.projectsexception.myapplist.open_16.apk.asc      100%[=====================================================================================================================>]     665  --.-KB/s    in 0s      

2016-12-29 19:36:02 (6.91 MB/s) - â€˜com.projectsexception.myapplist.open_16.apk.ascâ€™ saved [665/665]

--2016-12-29 19:36:02--  https://f-droid.org/repo/me.phh.superuser_1033.apk
Resolving f-droid.org (f-droid.org)... 107.150.51.2, 5.196.66.24
Connecting to f-droid.org (f-droid.org)|107.150.51.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1007563 (984K) [application/vnd.android.package-archive]
Saving to: â€˜me.phh.superuser_1033.apkâ€™

me.phh.superuser_1033.apk                            100%[=====================================================================================================================>] 983.95K  2.28MB/s    in 0.4s    

2016-12-29 19:36:03 (2.28 MB/s) - â€˜me.phh.superuser_1033.apkâ€™ saved [1007563/1007563]

--2016-12-29 19:36:03--  https://f-droid.org/repo/me.phh.superuser_1033.apk.asc
Resolving f-droid.org (f-droid.org)... 5.196.66.24, 107.150.51.2
Connecting to f-droid.org (f-droid.org)|5.196.66.24|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 648 [text/plain]
Saving to: â€˜me.phh.superuser_1033.apk.ascâ€™

me.phh.superuser_1033.apk.asc                        100%[=====================================================================================================================>]     648  --.-KB/s    in 0s      

2016-12-29 19:36:04 (121 MB/s) - â€˜me.phh.superuser_1033.apk.ascâ€™ saved [648/648]

--2016-12-29 19:36:04--  https://guardianproject.info/releases/orbot-latest.apk
Resolving guardianproject.info (guardianproject.info)... 162.247.75.177
Connecting to guardianproject.info (guardianproject.info)|162.247.75.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12457510 (12M) [application/vnd.android.package-archive]
Saving to: â€˜orbot-latest.apkâ€™

orbot-latest.apk                                     100%[=====================================================================================================================>]  11.88M  2.29MB/s    in 5.3s    

2016-12-29 19:36:10 (2.25 MB/s) - â€˜orbot-latest.apkâ€™ saved [12457510/12457510]

gpg: WARNING: unsafe permissions on homedir '/home/realname/Pets/mip/mission-improbable/packages'
gpg: assuming signed data in 'com.projectsexception.myapplist.open_16.apk'
gpg: Signature made Mon 11 Aug 2014 02:59:50 AM CDT
gpg:                using RSA key 7A029E54DD5DCE7A
gpg: /home/realname/Pets/mip/mission-improbable/packages/trustdb.gpg: trustdb created
gpg: Good signature from "F-Droid <admin@f-droid.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 37D2 C987 89D8 3119 4839  4E3E 41E7 044E 1DBA 2E89
     Subkey fingerprint: 802A 9799 0161 1234 6E1F  EFF4 7A02 9E54 DD5D CE7A
gpg: WARNING: unsafe permissions on homedir '/home/realname/Pets/mip/mission-improbable/packages'
gpg: assuming signed data in 'me.phh.superuser_1033.apk'
gpg: Signature made Thu 21 Jan 2016 01:55:26 PM CST
gpg:                using RSA key 7A029E54DD5DCE7A
gpg: Good signature from "F-Droid <admin@f-droid.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 37D2 C987 89D8 3119 4839  4E3E 41E7 044E 1DBA 2E89
     Subkey fingerprint: 802A 9799 0161 1234 6E1F  EFF4 7A02 9E54 DD5D CE7A
gpg: WARNING: unsafe permissions on homedir '/home/realname/Pets/mip/mission-improbable/packages'
gpg: assuming signed data in 'org.ethack.orwall_38.apk'
gpg: Signature made Fri 15 Jul 2016 04:05:41 AM CDT
gpg:                using RSA key 7A029E54DD5DCE7A
gpg: Good signature from "F-Droid <admin@f-droid.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 37D2 C987 89D8 3119 4839  4E3E 41E7 044E 1DBA 2E89
     Subkey fingerprint: 802A 9799 0161 1234 6E1F  EFF4 7A02 9E54 DD5D CE7A
/home/realname/Pets/mip/mission-improbable
creating verity.pk8 with no password
Generating RSA private key, 2048 bit long modulus
..+++
................+++
e is 65537 (0x10001)

./make_keys.sh: line 6: /home/realname/Pets/mip/mission-improbable/helper-repos/android-simg2img/generate_verity_key: No such file or directory
creating releasekey.pk8 with no password
Generating RSA private key, 2048 bit long modulus
...........+++
...................................+++
e is 65537 (0x10001)

/home/realname/Pets/mip/mission-improbable

Ensure OEM unlocking is enabled from Developer Options (see README.md)
Then reboot into fastboot (Boot holding Power and Volume Down) and hit enter

...
(bootloader) Device already unlocked!
FAILED (remote failure)
finished. total time: 0.016s

Ensure device is unlocked and hit enter

target reported max download size of 494927872 bytes
sending 'bootloader' (3532 KB)...
OKAY [  0.116s]
writing 'bootloader'...
OKAY [  0.205s]
finished. total time: 0.322s
rebooting into bootloader...
OKAY [  0.151s]
finished. total time: 0.201s
target reported max download size of 494927872 bytes
sending 'radio' (48728 KB)...
OKAY [  1.178s]
writing 'radio'...
OKAY [  2.163s]
finished. total time: 3.341s
rebooting into bootloader...
OKAY [  0.012s]
finished. total time: 0.062s
Archive:  ../image-angler-nmf26q.zip
 extracting: android-info.txt        
 extracting: cache.img               
 extracting: userdata.img            
 extracting: vendor.img              
 extracting: system.img              
 extracting: recovery.img            
 extracting: boot.img                
target reported max download size of 494927872 bytes
sending 'boot' (12097 KB)...
OKAY [  0.317s]
writing 'boot'...
OKAY [  0.178s]
finished. total time: 0.495s
target reported max download size of 494927872 bytes
erasing 'cache'...
OKAY [  0.029s]
sending 'cache' (5752 KB)...
OKAY [  0.157s]
writing 'cache'...
OKAY [  0.107s]
finished. total time: 0.293s
target reported max download size of 494927872 bytes
sending 'recovery' (17613 KB)...
OKAY [  0.446s]
writing 'recovery'...
OKAY [  0.256s]
finished. total time: 0.703s
target reported max download size of 494927872 bytes
erasing 'system'...
OKAY [  0.292s]
sending sparse 'system' 1/3 (483326 KB)...
OKAY [ 11.463s]
writing 'system' 1/3...
OKAY [  6.669s]
sending sparse 'system' 2/3 (483089 KB)...
OKAY [ 11.313s]
writing 'system' 2/3...
OKAY [  7.384s]
sending sparse 'system' 3/3 (265774 KB)...
OKAY [  6.445s]
writing 'system' 3/3...
OKAY [  4.331s]
finished. total time: 47.897s
target reported max download size of 494927872 bytes
erasing 'userdata'...
OKAY [  0.758s]
sending 'userdata' (138945 KB)...
OKAY [  3.334s]
writing 'userdata'...
OKAY [  2.185s]
finished. total time: 6.276s
target reported max download size of 494927872 bytes
sending 'vendor' (199296 KB)...
OKAY [  4.788s]
writing 'vendor'...
OKAY [  3.259s]
finished. total time: 8.047s

Copperhead successfully installed!
~/Pets/mip/mission-improbable/angler-nmf26q ~/Pets/mip/mission-improbable
~/Pets/mip/mission-improbable
cp: cannot stat 'keys/verity_key.pub': No such file or directory
[realname@3p1cpwn4g3 mission-improbable]$ 

`

**Comment by Girtab1352** [comment]
Short version:
When running ./run_all.sh, the install stops at Copperhead with the device still in bootloader, still unlocked. Device can boot into Copperhead successfully, but not a single other feature of this package is installed.  There seems to be an issue with generating the verity_key.pub file.

Long version:
I'm on a Nexus 6P.  This has been attempted from stock android with locked bootloader (OEM unlocking enabled, per instructions).  This has also been attempted from vanilla CopperheadOS with bootloader already unlocked (the state the phone is currently in, and ends up in after running the script.)  I am on Arch 2016 x86_64 GNU/Linux.  I'll happily provide other details of my install, just kindly give me commands to type.

Short version:
When running ./run_all.sh, I get the following errors, and install stops after installing CopperheadOS (in other words, no root, no orwall, no other recommended packages, no gapps, but Copperhead is installed, tested by starting phone from bootloader.)  I have seen mention of some of this here already, and the threads led me to this spot.  Correct me if I'm posting in error.  I have a long log file of every step I followed in bash, but here are the bits that popped out at me:

code:
`./make_keys.sh: line 6: /home/realname/Pets/mip/mission-improbable/helper-repos/android-simg2img/generate_verity_key: No such file or directory`

code:
`Copperhead successfully installed!
~/Pets/mip/mission-improbable/angler-nmf26q ~/Pets/mip/mission-improbable
~/Pets/mip/mission-improbable
cp: cannot stat 'keys/verity_key.pub': No such file or directory`

This is where the install stops, with the device still in bootloader, still unlocked.  Device can boot into Copperhead successfully, but not a single other feature of this package is installed.

Let me know if I can provide more detail.  The log file I copied and pasted from bash, I can post that here as well, but be warned, it's long.

**Comment by hugeguy** [comment]
which version of Linux are you using? Please do not use KALI LINUX

1. Do a clean install of Ubuntu
2. Install all required Prerequisites using apt-get
    fastboot & adb
    git, cpio, gcc, g++
    libssl-dev
    Java JRE/JDK 1.7+
3, ```
$ gpg --recv-keys 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
$ gpg angler-factory-2016.10.27.20.13.46.tar.xz.sig
$ tar -Jxvf angler-factory-2016.10.27.20.13.46.tar.xz
$ ./run_all.sh angler-nbd90z
```

**Comment by Girtab1352** [comment]
I am using arch.  not Kali.  That is actually in the original message.  here is uname -a
`Linux 3p1cpwn4g3 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
`
Here is fastboot --version
`fastboot version 7.0.0_r21
`
This version supports flashing unlock, as per the instructions in the Readme you mentioned.
Here is gcc --version
`gcc (GCC) 6.2.1 20160830
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
Here is cpio --version
`cpio (GNU cpio) 2.12
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Phil Nelson, David MacKenzie, John Oleynick,
and Sergey Poznyakoff.
`
Git was used to clone the repository.

jre7-openjdk and jre8-openjdk are both installed.  archlinux-java status gives
`Available Java environments:
  java-7-openjdk
  java-8-openjdk (default)
`
This would seem to cover all of the prerequisites, to include reading the manual.  Would you perhaps like to see a record of the steps I followed?

**Comment by isislovecruft** [comment]
It sounds like this issue was fixed? Please feel to reopen if otherwise, @maertsen.

For whatever it's worth, Mike and I have both been testing using a host operating system of Fedora 24 running inside a QubesOS AppVM.

**Comment by raininja** [comment]
I too was able to install copperhead from arch, but no verity key means no gapps which means no mobile data?  the run_all.sh script refers to "generate_verity_key"  binary that seemingly  must built from  a full  dev tree? might as well build the OS proper! I can use the  missing scripts manually to install the apks but when trying to install GApps it results in the red screen of doom and no boot. . . anyone feel like posting a copy of generate_verity_key ??
